# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed dependencies specified in requirements.txt
RUN pip install --no-cache-dir kafka-python cassandra-driver pandas pyarrow

# Run your Python script when the container launches
CMD ["python", "ali.py"]
